version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - curl -fsSL https://raw.githubusercontent.com/usdot-jpo-codehub/aws-codebuild-extras/master/install >> extras.sh
      - . ./extras.sh
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - CODEBUILD_RESOLVED_SOURCE_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:-$IMAGE_TAG}"
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
  build:
    commands:
      - npm install -g elasticdump
      - mkdir -p data
      - elasticdump --input=$DEPLOYED_ELASTICSEARCH_URL/repositories --output=data/repositories-data.json --type=data
      - docker build -t $IMAGE_URI:$IMAGE_TAG .
  post_build:
    commands:
      - |
        if [ "$CODEBUILD_GIT_BRANCH" = "master" ] || [ "$CODEBUILD_GIT_BRANCH" = "development" ]; then
          docker push "$IMAGE_URI:$IMAGE_TAG";
          docker tag "$IMAGE_URI:$IMAGE_TAG" "$IMAGE_URI:latest"
          docker push "$IMAGE_URI:latest";
        fi
